git:
  depth: 5

language: node_js

node_js:
  - "10"

script:
  - ifconfig -a
  - npm run ci

after_success:
  - npm run coverage

matrix:
  fast_finish: true

notifications:
  email:
    - joshua@mervine.net
    - bootstrap@maxcdn.com

cache:
  directories:
    - node_modules
